### ISSUE TITLE
possible ideas

### ISSUE THREAD

**Issue by Asterveila** [iAndyHD3/SoundEffects#2]
idk if this is still gonna get updated but heres some ideas i had for it i thought would be cool

•sound effect for slow speeds (0.5, 1)
•sound effect for faster speeds (2, 3, 4)
•sound effect when crossing a teleport portal
•sound effect when crossing a gamemode portal
•sound effect when clicking on the UFO
•menu sound effects (exiting out of a menu, clicking a button, choosing icons)
•level complete effects (1 sound effect for every orb for example)
don't know how many are possible but would love to see some of these

**Comment by iAndyHD3** [comment]
thanks for the suggestions, sure i will try to add as many as i can

**Comment by Asterveila** [comment]
cool ill look forward to seeing them:)!

**Comment by iAndyHD3** [comment]
updated with some of the sounds here and more, enjoy!! closing
